### ISSUE TITLE
Problem with kepub

### ISSUE THREAD

**Issue by BeckyDTP** [geek1011/kepubify#12]
Today for the first time I used the kepubify program.
After the conversion, I copied the file to the reader to see if the kepub format really is so great. Unfortunately, it turned out that the file looks worse than a regular epub.

[EPUB (two pages)](https://i.imgur.com/ihJAm8Ih.jpg)
[KEPUB (two pages)](https://i.imgur.com/AQrltlih.jpg)

I also attach the source file.
[Sample.zip](https://github.com/geek1011/kepubify/files/1569696/Sample.zip)

**Comment by geek1011** [comment]
Ok. I see. Kepubify is mainly optimized for English books, as the sentence splitting does not handle other languages yet. 

Does this occur then using the calibre kepub conversion plugin?

**Comment by BeckyDTP** [comment]
You're right. Conversion in calibre gives identical results.

**Comment by geek1011** [comment]
I may work on this if I have time. For now, it may be better just to use epub.

**Comment by BeckyDTP** [comment]
Great. In Poland there are many users Kobo.
