### ISSUE TITLE
Whitespace is swallowed after italic

### ISSUE THREAD

**Issue by lyderic** [geek1011/kepubify#14]
Hi,

kepub files produced with kepubify "swallow" whitespaces after words in italic.

For example, I used it with the French epub file found here:
https://www.ebooksgratuits.com/newsendbook.php?id=2610&format=epub

In the "Préface" (foreword), whenever the italic word _Belgica_ is used, the following word becomes glued right next to it, without whitespace, for example:

...l'exploration de la <i>Belgica</i>précède...

instead of:

...l'exploration de la _Belgica_ précède...

I am using version 1.3.5 under Linux. I have also build the current "dev" version from source, it didn't help.

Thanks for this fantastic tool!

Cheers,
L.

**Comment by geek1011** [comment]
Thanks for reporting this issue! I have looked, and can confirm the issue.

I'll fix it sometime this week.

**Comment by geek1011** [comment]
This should be fixed now.

**Comment by lyderic** [comment]
Many thanks. I confirm that it is fixed for the epub I reported. It should
be the case for all other epubs from this source. If not, I will allow
myself to let you know when a problem pops up.

Cheers,
Lyderic
