### ISSUE TITLE
[linux] Still epub

### ISSUE THREAD

**Issue by Z3DNA** [geek1011/kepubify#18]
Hi,
I tried kepubify on ubuntu 17 yesterday. 
Everything is fine, the conversion is running but when I check my original epub file is still an epub file. 
I'm very interesting to get a solution to convert in kepub on linux and currently i have found no one. 
Thks

**Comment by onodera-punpun** [comment]
it should create a new directory with the kebup files

**Comment by geek1011** [comment]
Have a look at the [documentation](https://geek1011.github.io/kepubify].

For batch conversion, kepubify creates a new directory with the suffix `_converted`. For single conversion, kepubify creates a new file in the same directory with the extension `.kepub.epub`.

**Comment by Z3DNA** [comment]
I tried a single conversion but nothing happened I just have my original file after the process.

**Comment by onodera-punpun** [comment]
>Note that a kepub formatted book needs the extension to be .kepub.epub, that is two extensions. Otherwise it will not recognize the book as different from a normal epub. 

https://wiki.mobileread.com/wiki/Kepub

**Comment by geek1011** [comment]
I'm going to close this issue now. If you have anymore questions, feel free to reopen it.
