### ISSUE TITLE
Incorrect page displayed on e-reader

### ISSUE THREAD

**Issue by tjaadvd** [geek1011/kepubify#19]
When I click on a link in the ToC of a book, my Kobo e-reader displays the wrong page number. For example, when I click on a link op page 2 that sends me to the middle of the book, my e-reader shows that the current page number is 3 (it should be something like 200).
Is this a known issue or is there a known workaround?

Thanks for making this btw.

**Comment by tjaadvd** [comment]
I have the same issue with the conversion plugin in Calibre.

**Comment by geek1011** [comment]
Thanks for reporting this issue. Are the page numbers correct when you turn pages normally? Also, can you send me the epub so I can have a look?

**Comment by tjaadvd** [comment]
Yes the page numbers are correct when I turn the page normally. I'll send you the epub via email shortly.

**Comment by geek1011** [comment]
OK. This looks like an issue with the Kobo firmware. I have opened an issue: kobolabs/Kobo-Reader#71

**Comment by geek1011** [comment]
Do you still have this issue with the latest firmware release (4.8.10956)?

**Comment by geek1011** [comment]
I'm going to close this for now. Feel free to reopen it if it still does not work.
