### ISSUE TITLE
epubcheck: Fatal Error while parsing file 'The entity "nbsp" was referenced, but not declared.'.

### ISSUE THREAD

**Issue by daniel-j** [geek1011/kepubify#26]
Solution: Replace `&nbsp;` with `&#160;` (or `&#xA0;` if you prefer hex) in the following code:
https://github.com/geek1011/kepubify/blob/c5af6bc6cfc350284665091a6ad16e6c29abd12e/kepub/content.go#L308

**Comment by geek1011** [comment]
Thanks for reporting this issue! I've fixed it now and will release it in the next version.
