### ISSUE TITLE
On windows, kepubify never stops

### ISSUE THREAD

**Issue by JeFrRe** [geek1011/kepubify#3]
On windows, as a command line tool, the application never seems to stop.
I have to kill the process from the task manager (or send a ctrl+c in a dos box).

After examination of the code, it makes sense since I saw
```
if runtime.GOOS == "windows" {
    time.Sleep(5000 * time.Second)
}
```

Is this really normal? Because waiting 5000 seconds for the process to finish is quite long. :-)

**Comment by geek1011** [comment]
It's so you can see the output before the window disappears. :smiley:

**Comment by JeFrRe** [comment]
Hello,

The only problem is if I want to chain some conversions, it waits
indefinitely or for x conversion opens x windows which I have to close
manually.

I had already guessed the utility of the delay, but 5000 seconds doesn't
make it much of a command line utility. Or could you put up a flag to
disable the delay or some other way of making it more "batch script
friendly"?

JF

**Comment by geek1011** [comment]
I will do that.

On Aug 19, 2017 8:20 AM, JeFrRe <notifications@github.com> wrote:
Hello,

The only problem is if I want to chain some conversions, it waits
indefinitely or for x conversion opens x windows which I have to close
manually.

I had already guessed the utility of the delay, but 5000 seconds doesn't
make it much of a command line utility. Or could you put up a flag to
disable the delay or some other way of making it more "batch script
friendly"?

JF

**Comment by geek1011** [comment]
Finished. See version 1.1.4.

Also keep in mind that there are known conversion issues on windows.
