### ISSUE TITLE
Mac & Kepubify

### ISSUE THREAD

**Issue by GrayWolf9368** [geek1011/kepubify#32]
Your Mac install produces, for me, a 64 bit Darwin.dms file,I don't this this should be, but being a novice terminal user .... Please, can you help me with the steps necessary in MacOs 10.12.6  Calibre will work, I know, but on the surface I think this should be a superior method.

**Comment by geek1011** [comment]
What do you mean by a "dms file"?

To use kepubify, you download it, and open Terminal. You then type `chmod +x `, and drag it into the terminal and press enter. After, you type can drag kepubify into the terminal, then a book or a folder of books, and press enter.

**Comment by geek1011** [comment]
Since there hasn't been any response, I'm going to close this issue. If you still have this issue, feel free to reopen it.
