### ISSUE TITLE
Kepubify doesnt start in Ubuntu 18.04

### ISSUE THREAD

**Issue by Der-Bauer** [geek1011/kepubify#38]
Hey geek1011 I´ve got problems to start your program but it doesnt want run i made steps 

Download kepubify
Open a terminal
Type cd ~/Downloads (or whatever location you downloaded kepubify to) and press enter
Type chmod +x kepubify-linux-* and press enter 
I using Ubuntu Budgie 18.04 64 Bit version  did i miss something  ?

**Comment by geek1011** [comment]
Did you actually try running it (`./kepubify-linux-* /path/to/book.epub`)?

**Comment by Der-Bauer** [comment]
Hey geek1011 that i was looking for it works thank for helping me out ;=)

**Comment by geek1011** [comment]
No problem.
