### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by vitorgalvao** [geek1011/kepubify#4]
Thank you for making this tool. I’ve been looking for something like it for quite some time, and it seems like I finally found it. It seems to work well, and I’m eager to try it further.

[Homebrew](https://brew.sh/) is a popular package manager on macOS, and I like to install all my tools through it, so [I’ve made a formula](https://github.com/vitorgalvao/homebrew-kepubify). Anyone can now install `kepubify` with `brew install vitorgalvao/kepubify/kepubify`. I’m following the releases page for this repo so I know when a new version is out.

Making this issue to thank you for the tool and to inform about the formula, in case you want to include it in the README, or if you’d like to be the one to manage the formula yourself, officially (it takes little work and I can help you set everything up, if you’re interested).

**Comment by geek1011** [comment]
Thanks! 

I use macOS a bit, but not enough to justify maintaining a homebrew formula. I will link to yours. Thanks for making it.

**Comment by geek1011** [comment]
I have updated the README and the website with information about your package.

**Comment by vitorgalvao** [comment]
Thank you. If you ever want to take up the formula yourself, just let me know. Otherwise, I’m happy to keep it updated in my repo.

There’s a small typo on the website — it says “Thanks to @vitorgalvo” (missing a “a”), but the link and code are correct.

Thank you again for the tool!

**Comment by vitorgalvao** [comment]
@geek1011 Update on this, `kepubify` now has enough stars to be included in the main Homebrew repository.

Once it’s done, @commitay [will submit a PR to this repo](https://github.com/vitorgalvao/homebrew-kepubify/pull/11#issue-322684528) to change the install instructions. There’s nothing that needs to be done on your side other than merging the updated instructions, everything else will remain the same.

**Comment by geek1011** [comment]
Thanks! I noticed those PRs earlier today.

**Comment by commitay** [comment]
PR to update `brew install` instructions. https://github.com/geek1011/kepubify/pull/41

Thank you @geek1011 for making this tool and @vitorgalvao for running the tap!
