### ISSUE TITLE
Converted file fails to open on Kobo H2O

### ISSUE THREAD

**Issue by rokweom** [geek1011/kepubify#50]
I'm trying to convert a (rather simple, I think) epub file, but even after many modifications to the input file the converted kepub fails to open, giving an "Oops!, This document couldn't be opened" error on my Kobo Aura H2O. I've verified the input epub file with epubcheck 4.2.2 and it is fully compliant. I've tried playing with kepubify settings (smarten-punctuation, hyphenate) and it didn't help. The original epub transfered to the reader opens just fine.

Here are the files in question: [epub+kepub](https://mega.nz/file/i4pywSzK#UzBNz8xQLZKIsCsvePihqWh7x5TaEMO_NB41yOTwaAM)

**Comment by geek1011** [comment]
Does it open if you just rename the file to `.kepub.epub`? If not, it's a bug in the Kobo itself (or an issue with the book) and you'll probably to contact Kobo about it.

**Comment by rokweom** [comment]
Turns out the problem was caused by exclamation mark in the filename. After removing it opens just fine. 
It's interesting that epub with the same filename doesn't cause any problem. Indeed, it looks like a bug in the Kobo software.

**Comment by Yuubari** [comment]
For the record: this also happens if any part of the path contains an exclamation mark (like a subdirectory). Kobo Libra H2O.

**Comment by geek1011** [comment]
That's because the exclamation mark is used to separate the location identifier in the database.
