### ISSUE TITLE
ARM binary 32bit or 64bit?

### ISSUE THREAD

**Issue by CHBMB** [geek1011/kepubify#51]
Hi, I can see you've produced an array of cross platform binaries, but I'm wondering if the arm binary is 32bit or 64bit?

With the advent of the RPi4 and the new 64bit Raspberry OS I think there's a case for both 32bit arm binaries for the older raspberry pi models and a 64bit arm binary for the newer architecture, although I understand that would be more work for yourself, at the least I think it might be helpful to clarify which arm architecture it's for like you currently do with the Linux version.

Thanks for reading and for all your work.

**Comment by geek1011** [comment]
The arm binary is 32bit (note that 64bit is aarch64). I can easily add aarch64 binaries to the release script, and I'll do that for the next version.

**Comment by CHBMB** [comment]
Awesome, I was 98% sure they'd be 32 bit.  Forgive me for the terminology slip up. 

> I can easily add aarch64 binaries to the release script, and I'll do that for the next version

Appreciate that, I really do.  Thanks mate.

I'll leave the decision on whether to close this (non)issue to yourself, clearly my question has been answered, just not sure if you like to leave things open to track them, or whether you prefer to clear the decks.

**Comment by geek1011** [comment]
This has been released in v3.1.3.
