### ISSUE TITLE
File masks don't work on Windows

### ISSUE THREAD

**Issue by AlexeiA** [geek1011/kepubify#53]
Given command from the examples:
`> kepubify -o "converted" *.epub`
`Error: scan input "*.epub": CreateFile *.epub: The filename, directory name, or volume label syntax is incorrect.`

**Comment by geek1011** [comment]
Type `dir` and see if there are actually epub files in the current directory. If not, then `cd` to it. If there are files but it still doesn't work, try using PowerShell instead.

**Comment by AlexeiA** [comment]
The same error from PowerShell. By the way, if I try non-existing file name, the error is slighly different:
`Error: scan input "1.epub": CreateFile 1.epub: The system cannot find the file specified.`

**Comment by geek1011** [comment]
This might be because of the 4-character epub extension on Windows (meaning that wildcards don't work as expected) (random guess: try `*.epu`). As a workaround, you could convert the current dir (`.`) to `./converted` (it will ignore the converted files).

**Comment by AlexeiA** [comment]
Yes, using directory instead of mask works, thanks! So this is not an issue for me anymore :)
Btw, when using mask the program returns error at line 55: 
`inputInfo, err := os.Stat(input)`
Out of curiosity, does this line work on unix if input is "*.epub"?

**Comment by geek1011** [comment]
Yes, that works on everything but Windows.

You are correct that the error comes from there, but it's a red herring. The issue is because cmd doesn't expand it correctly (the wildcard processing is done by the shell).

Does `*epu*` work?

**Comment by AlexeiA** [comment]
> Does *.epu* work?
No, cmd and PowerShell always pass wildcards as-is :(

**Comment by geek1011** [comment]
That's interesting. I wasn't aware of that before. I might add wildcard handling directly if it's running on Windows.
